export type NotificationType =
  | 'expiry_7d'
  | 'expiry_3d'
  | 'expiry_1d'
  | 'expired'
  | 'renewal_reminder'
  | 'reservation_confirmed'
  | 'reservation_new'
  | 'reservation_cancelled'
  | 'reservation_accepted'
  | 'points_earned'
  | 'purchase_completed'
  | 'subscription_new'
  | 'loyalty_request_new'
  | 'loyalty_fulfilled'
  | 'loyalty_rejected'
  | 'room_almost_full'
  | 'seat_swap_request_new'
  | 'seat_swap_accepted'
  | 'seat_swap_denied'
  | 'announcement_new'
  | 'seat_removed_by_staff'
  | 'seat_changed_freely'

export type NotificationChannel = 'email' | 'sms' | 'whatsapp' | 'inapp'
